name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: release apk sign
      run: |
        echo "给apk增加签名"
        cp $GITHUB_WORKSPACE/.github/workflows/test.keystore $GITHUB_WORKSPACE/app/test.keystore
        sed '$a\RELEASE_STORE_FILE=./test.keystore'          $GITHUB_WORKSPACE/gradle.properties -i
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleRelease && find app/build/outputs
    - name: Upload apk
      uses: actions/upload-artifact@v1
      with:
        name: app-armeabi-v7a-release-unsigned.apk
        path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk

